services:
  - type: web
    name: workplus-backend
    env: node
    plan: standard
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: workplus-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://workplus-murex.vercel.app
      - key: SMTP_HOST
        value: smtp.office365.com
      - key: SMTP_PORT
        value: 587
      - key: FROM_EMAIL
        sync: false
      - key: HR_EMAIL
        sync: false

databases:
  - name: workplus-db
    databaseName: workpluspro
    user: workplus_user
    plan: standard
